version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    restart: always
    environment:
      - CONFIG_FILE=config.toml

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3009:3000"
    restart: always
    environment:
      - REACT_APP_SERVER_URL=http://server:7000/ws
    depends_on:
      - server

volumes:
  config:
